language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - PANDAS_VERSION=v0.13.1
  - PANDAS_VERSION=v0.14.1
  - PANDAS_VERSION=master

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev libspatialindex-dev libspatialindex1
#  - sudo -u postgres psql -c "drop database if exists test_geopandas"
#  - sudo -u postgres psql -c "create database test_geopandas"
#  - sudo -u postgres psql -c "create extension postgis" -d test_geopandas

install:
  - ci/install.sh

script:
  - py.test tests --cov geopandas -v --cov-report term-missing

after_success:
  - coveralls
